### ISSUE TITLE
Deploying boards to the root path of a (sub) domain without path prefix

### ISSUE THREAD

**Issue by DMW007** [isw-kudos/huddo-docs#1]
Hello Huddo-Team,
since you told me that [kudos-docs](https://github.com/isw-kudos/kudos-docs) is deprecated (archiving and the notice in the readme is a good idea, could you may include this in your workflow earlier next time to avoid confusion?), I'll now post my issues/PR here. 

We've a subdomain for boards, on my testserver it's `boards.cnx65-k8s.hobel.internal`. So a context path which would result in urls like `boards.cnx65-k8s.hobel.internal/boards` doesn't really make sense here. I also prefer subdomains instead of path prefixes since those are less error-prone from my experience.

So I set the ingress for the web application to `/`, while the API remains on the `/api-boards` path. Setting `APP_URI_PATH: /` breaks boards, since it seems that this would result in a base path of `//` in the application. To work around this, my current approach is to check if the path is equal to `/` and set `APP_URI_PATH` to an empty string in this case, which results in `/` as base path instead of `//`

```yaml
global:
  repository: iswkudos/kudos-boards
  imageTagSuffix: '{{ image_tag_suffix }}'
  env:
    APP_URI: '{{ app_uri }}'
    # If boards is installed on the root dir (/), it doesn't work to specify / here -> would result in "//" basedir, avoids that dependent files are loaded
    APP_URI_PATH: '{% if (path != "/") %}{{ path }}{% endif %}'
```
Is this a supported configuration? Do you see any reasony why it should cause issues when having `APP_URI_PATH: ''` set? I cannot fully test this since the dynamic generated URL of my testserver doesn't match the one from our old test system in the licence, but as fair as I can say it seems to work, since all ressources were properly loaded and the UI shows no issues.

It would make sense if a subdomain is used. If you can support this, I'd suggest to add some notice in the documentation that `APP_URI_PATH: ''` has to be set in this case instead of `APP_URI_PATH: '/'`.
